# Ordinal DATA ()

In [ ]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('customer.csv')
df.sample(5)


age  gender review education purchased
19   97    Male   Poor        PG       Yes
10   98  Female   Good        UG       Yes
40   39    Male   Good    School        No
46   64  Female   Poor        PG        No
25   57  Female   Good    School        No

### Eliminate Unnecessary Columns

In [7]:
df = df.iloc[:,2:]
df.sample(5)


review education purchased
16     Poor        UG       Yes
13  Average    School        No
44  Average        UG        No
40     Good    School        No
25     Good    School        No

### Train_Test_Split

In [32]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1:],test_size=0.2)

### Import_OrdinalEncoder

In [34]:
from sklearn.preprocessing import OrdinalEncoder
x_train

review education
20  Average    School
48     Good        UG
35     Poor    School
7      Poor    School
5   Average    School
1      Poor        UG
18     Good    School
47     Good        PG
42     Good        PG
45     Poor        PG
8   Average        UG
24  Average        PG
43     Poor        PG
33     Good        PG
10     Good        UG
0   Average    School
40     Good    School
6      Good    School
25     Good    School
30  Average        UG
31     Poor    School
22     Poor        PG
44  Average        UG
3      Good        PG
9      Good        UG
26     Poor        PG
17     Poor        UG
11     Good        UG
13  Average    School
2      Good        PG
12     Poor    School
49     Good        UG
27     Poor        PG
14     Poor        PG
37  Average        PG
34  Average    School
28     Poor    School
29  Average        UG
19     Poor        PG
46     Poor        PG

#### Define Categories

In [35]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])


In [36]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

### Transform Ordinal Encoding

In [40]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)
x_train

array([[1., 0.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [1., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [1., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [0., 2.]])

In [41]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

### Label Encoding

In [42]:
from sklearn.preprocessing import LabelEncoder

In [43]:
le = LabelEncoder()
le.fit(y_train)

c:\Users\ripon\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LabelEncoder()

In [44]:
LabelEncoder()
le.classes_

array(['No', 'Yes'], dtype=object)

In [45]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

c:\Users\ripon\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
c:\Users\ripon\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [46]:
y_train

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0])

# Norminal DATA 

In [47]:
import numpy as np
import pandas as pd

In [49]:
df = pd.read_csv('cars.csv')
df.sample(5)

brand  km_driven    fuel         owner  selling_price
3705  Maruti      80000  Petrol   First Owner         810000
4611    Tata     101200  Diesel  Second Owner         350000
2435    Ford     110000  Diesel  Second Owner          90000
922   Maruti       1620  Petrol   First Owner        1040000
6661  Maruti      35000  Petrol   First Owner         240000

In [50]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [54]:
df['brand'].value_counts()
df['brand'].nunique()

32

In [52]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

### 1. One Hot Encoding Using Pandas

In [58]:
pd.get_dummies(df,columns=['fuel','owner'])

brand  km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  \
0      Maruti     145500         450000     False         True     False   
1       Skoda     120000         370000     False         True     False   
2       Honda     140000         158000     False        False     False   
3     Hyundai     127000         225000     False         True     False   
4      Maruti     120000         130000     False        False     False   
...       ...        ...            ...       ...          ...       ...   
8123  Hyundai     110000         320000     False        False     False   
8124  Hyundai     119000         135000     False         True     False   
8125   Maruti     120000         382000     False         True     False   
8126     Tata      25000         290000     False         True     False   
8127     Tata      25000         290000     False         True     False   

      fuel_Petrol  owner_First Owner  owner_Fourth & Above Owner  \
0           False               True                       False   
1           False              False                       False   
2            True              False                       False   
3           False               True                       False   
4            True               True                       False   
...           ...                ...                         ...   
8123         True               True                       False   
8124        False              False                        True   
8125        False               True                       False   
8126        False               True                       False   
8127        False               True                       False   

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0                  False                 False              False  
1                   True                 False              False  
2                  False                 False               True  
3                  False                 False              False  
4                  False                 False              False  
...                  ...                   ...                ...  
8123               False                 False              False  
8124               False                 False              False  
8125               False                 False              False  
8126               False                 False              False  
8127               False                 False              False  

[8128 rows x 12 columns]

### 2. K-1 One Hot Encoding

In [57]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0      Maruti     145500         450000         True     False        False   
1       Skoda     120000         370000         True     False        False   
2       Honda     140000         158000        False     False         True   
3     Hyundai     127000         225000         True     False        False   
4      Maruti     120000         130000        False     False         True   
...       ...        ...            ...          ...       ...          ...   
8123  Hyundai     110000         320000        False     False         True   
8124  Hyundai     119000         135000         True     False        False   
8125   Maruti     120000         382000         True     False        False   
8126     Tata      25000         290000         True     False        False   
8127     Tata      25000         290000         True     False        False   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                          False               False                 False   
1                          False                True                 False   
2                          False               False                 False   
3                          False               False                 False   
4                          False               False                 False   
...                          ...                 ...                   ...   
8123                       False               False                 False   
8124                        True               False                 False   
8125                       False               False                 False   
8126                       False               False                 False   
8127                       False               False                 False   

      owner_Third Owner  
0                 False  
1                 False  
2                  True  
3                 False  
4                 False  
...                 ...  
8123              False  
8124              False  
8125              False  
8126              False  
8127              False  

[8128 rows x 10 columns]

### 3. One hot encoding Using Sklearn

In [70]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=2)

In [71]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [72]:
X_train.head()

brand  km_driven    fuel         owner
6277     Tata     110000  Diesel  Second Owner
5473    Honda     120000  Petrol  Second Owner
92    Hyundai      45000  Petrol  Second Owner
4906   Maruti      42000  Petrol   First Owner
1126   Toyota      25538  Petrol   First Owner

In [82]:
X_test.head()

brand  km_driven    fuel         owner
3179    Maruti      28000  Petrol   First Owner
4616  Mahindra      80000  Diesel  Second Owner

## Import OHE: SK Learn

In [74]:
from sklearn.preprocessing import OneHotEncoder

In [97]:
ohe = OneHotEncoder(drop='first', dtype=np.int32)
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [98]:
X_test_new = ohe.transform(X_test[['fuel','owner']]).toarray()
X_train_new

array([[1, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 1]])

In [99]:
X_train_new.shape

(8126, 7)

In [100]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Tata', 110000, 1, ..., 1, 0, 0],
       ['Honda', 120000, 0, ..., 1, 0, 0],
       ['Hyundai', 45000, 0, ..., 1, 0, 0],
       ...,
       ['Mahindra', 19700, 0, ..., 0, 0, 0],
       ['Maruti', 10000, 0, ..., 0, 0, 0],
       ['Hyundai', 100000, 0, ..., 0, 0, 1]], dtype=object)